#!/bin/bash
# ngpc-space bootstrap — fresh install or install-over-partial
# Usage: ./bootstrap.sh [--check-only]
set -euo pipefail

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[0;33m'; BLU='\033[0;34m'; NC='\033[0m'
CHECK_ONLY=0; ISSUES=0; FIXED=0
[[ "${1:-}" == "--check-only" ]] && CHECK_ONLY=1

ROOT="$(cd "$(dirname "$0")" && pwd)"

ok()   { echo -e "  ${GRN}OK${NC}  $1"; }
warn() { echo -e "  ${YEL}!!${NC}  $1"; ISSUES=$((ISSUES+1)); }
fail() { echo -e "  ${RED}XX${NC}  $1"; ISSUES=$((ISSUES+1)); }
fix()  { echo -e "  ${BLU}>>${NC}  $1"; FIXED=$((FIXED+1)); }

ensure_dir() {
    if [[ -d "$ROOT/$1" ]]; then ok "$1/"; else
        warn "$1/ missing"
        [[ $CHECK_ONLY -eq 0 ]] && { fix "mkdir $1"; mkdir -p "$ROOT/$1"; }
    fi
}

# ── Host tools ──────────────────────────────────────────────
echo ""; echo "=== Host Tools ==="
for cmd in wine winepath make mednafen; do
    if command -v $cmd &>/dev/null; then ok "$cmd"; else fail "$cmd not found"; fi
done

# ── Toolchain location ─────────────────────────────────────
echo ""; echo "=== Toolchain ==="

# Search common locations
TBIN=""
for try in \
    "${TOOLCHAIN_SRC:-}/T900/BIN" \
    "$ROOT/toolchain/T900/BIN" \
    "/media/gandalf/datarecords/ngpcbins/T900/BIN" \
    "/media/gandalf/datarecords/ngpcbins/ngpcbins/T900/BIN"; do
    if [[ -f "$try/cc900.exe" ]]; then TBIN="$try"; break; fi
done

if [[ -n "$TBIN" ]]; then
    ok "Toolchain found: $TBIN"
    for exe in cc900.exe tulink.exe tuconv.exe s242ngp.exe; do
        if [[ -f "$TBIN/$exe" ]]; then ok "  $exe"; else fail "  $exe missing"; fi
    done

    # Derive paths
    TROOT="$(dirname "$TBIN")"
    RTLIB="$TROOT/LIB/c900ml.lib"
    INCDIR="$TROOT/INCLUDE"
    if [[ -f "$RTLIB" ]]; then ok "  c900ml.lib"; else fail "  c900ml.lib not at $RTLIB"; fi
    if [[ -d "$INCDIR" ]]; then ok "  INCLUDE/"; else fail "  INCLUDE/ not at $INCDIR"; fi

    # Write toolchain.mk so Makefile can find everything
    if [[ $CHECK_ONLY -eq 0 ]]; then
        cat > "$ROOT/toolchain.mk" <<EOF
# Auto-generated by bootstrap.sh — edit or re-run bootstrap if paths change
TBIN    = $TBIN
TROOT   = $TROOT
RTLIB   = $RTLIB
INCDIR  = $(winepath -w "$INCDIR" 2>/dev/null || echo "$INCDIR")
EOF
        fix "Wrote toolchain.mk"
    fi
else
    fail "Toolchain not found. Set TOOLCHAIN_SRC=/path/to/ngpcbins and re-run"
    echo "       Or symlink: ln -s /path/to/ngpcbins $ROOT/toolchain"
fi

# ── Wine path test ──────────────────────────────────────────
echo ""; echo "=== Wine Paths ==="
if command -v winepath &>/dev/null; then
    WTEST=$(winepath -w "$ROOT" 2>/dev/null || echo "FAIL")
    if [[ "$WTEST" != "FAIL" ]]; then ok "Project root → $WTEST"; else warn "winepath failed"; fi
fi

# ── Project dirs ────────────────────────────────────────────
echo ""; echo "=== Project Structure ==="
for d in src common lcf build bin assets tools lib; do ensure_dir "$d"; done

# ── Core files ──────────────────────────────────────────────
echo ""; echo "=== Core Files ==="
for f in Makefile common/ngpc.h common/carthdr.h common/sys.c common/sys.h src/main.c lcf/space.lcf; do
    if [[ -f "$ROOT/$f" ]]; then ok "$f"; else warn "$f missing"; fi
done

# ── Build test ──────────────────────────────────────────────
echo ""; echo "=== Build Test ==="
if [[ $CHECK_ONLY -eq 0 && -f "$ROOT/Makefile" && -f "$ROOT/toolchain.mk" ]]; then
    if cd "$ROOT" && make clean >/dev/null 2>&1; make 2>&1; then
        if ls "$ROOT"/bin/*.ngp >/dev/null 2>&1; then
            ok "ROM built successfully"
            ls -la "$ROOT"/bin/*.ngp
        else
            warn "make ran but no .ngp produced"
        fi
    else
        fail "Build failed"
    fi
else
    echo "  Skipped (need Makefile + toolchain.mk; run without --check-only)"
fi

# ── Summary ─────────────────────────────────────────────────
echo ""
if [[ $ISSUES -eq 0 ]]; then echo -e "${GRN}All good.${NC}"
elif [[ $CHECK_ONLY -eq 1 ]]; then echo -e "${YEL}$ISSUES issue(s). Run without --check-only to fix.${NC}"
else echo -e "${YEL}$ISSUES issue(s), $FIXED fixed.${NC}"; fi
echo ""
