# ngpc-space — NGPC Space Collection Build
# Requires: toolchain.mk (generated by bootstrap.sh)

-include toolchain.mk

# Project
TARGET  = zork
ROM     = bin/$(TARGET).ngp
LCF     = lcf/zork.lcf
SYSLIB  = lib/system.lib

# Sources: common/ + src/
COMMON_SRCS = $(wildcard common/*.c)
GAME_SRCS   = $(wildcard src/*.c)

# Objects: flatten into build/
# IMPORTANT: src_main.rel MUST be first — it contains the ROM header
COMMON_OBJS = $(patsubst common/%.c,build/common_%.rel,$(COMMON_SRCS))
GAME_OBJS   = build/src_main.rel $(filter-out build/src_main.rel,$(patsubst src/%.c,build/src_%.rel,$(GAME_SRCS)))
ALL_OBJS    = $(GAME_OBJS) $(COMMON_OBJS)

# Wine path helper
WP = $(shell winepath -w $(CURDIR)/$1)

.PHONY: all clean run check

all: $(ROM)

# ── Compile ─────────────────────────────────────────────────
build/common_%.rel: common/%.c | build
	cd $(TBIN) && wine cc900.exe -c \
		-I'$(INCDIR)' \
		-I'$(call WP,common)' \
		-o '$(call WP,$@)' \
		'$(call WP,$<)'

build/src_%.rel: src/%.c | build
	cd $(TBIN) && wine cc900.exe -c \
		-I'$(INCDIR)' \
		-I'$(call WP,common)' \
		-o '$(call WP,$@)' \
		'$(call WP,$<)'

# ── Link — matches working Hang-On order exactly ───────────
# tulink args: LCF, system.lib, c900ml.lib, then objects (main first)
build/$(TARGET).abs: $(ALL_OBJS)
	cd $(TBIN) && wine tulink.exe -la \
		-o '$(call WP,$@)' \
		'$(call WP,$(LCF))' \
		'$(call WP,$(SYSLIB))' \
		'$(shell winepath -w $(RTLIB))' \
		$(foreach o,$(ALL_OBJS),'$(call WP,$(o))')

# ── Convert ─────────────────────────────────────────────────
build/$(TARGET).s24: build/$(TARGET).abs
	cd $(TBIN) && wine tuconv.exe -Fs24 '$(call WP,$<)'

# ── ROM ─────────────────────────────────────────────────────
$(ROM): build/$(TARGET).s24 | bin
	cd $(TBIN) && wine s242ngp.exe $(TARGET).s24
	mv -f $(TBIN)/$(TARGET).ngp $(CURDIR)/$(ROM) 2>/dev/null || true
	@echo "  ROM: $(ROM)"

# ── Run ─────────────────────────────────────────────────────
run: $(ROM)
	mednafen $(ROM)

# ── Check (bootstrap) ──────────────────────────────────────
check:
	./bootstrap.sh --check-only

# ── Dirs ────────────────────────────────────────────────────
build:
	mkdir -p build

bin:
	mkdir -p bin

# ── Clean ───────────────────────────────────────────────────
clean:
	rm -f build/*.rel build/*.abs build/*.s24
	rm -f $(ROM)
